# Generated by Django 3.2.8 on 2021-10-12 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='juego',
            fields=[
                ('id_juego', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255, null=True, verbose_name='Nombre')),
                ('año', models.DateField(max_length=255, null=True, verbose_name='Fecha')),
                ('developer', models.CharField(max_length=255, null=True, verbose_name='Desarrollador')),
                ('publisher', models.CharField(max_length=255, null=True, verbose_name='Editor')),
                ('descripcion', models.CharField(max_length=255, null=True, verbose_name='Descripcion')),
                ('valoracion', models.IntegerField(null=True, verbose_name='Calificacion')),
                ('imagen', models.ImageField(upload_to=None)),
            ],
        ),
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('nombre', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Nombre Usuario')),
                ('contraseña', models.CharField(max_length=100, null=True, verbose_name='Contraseña')),
                ('correo', models.EmailField(max_length=100, null=True, verbose_name='E-mail')),
            ],
        ),
        migrations.CreateModel(
            name='comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=1000, null=True, verbose_name='Comentario')),
                ('id_juego', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.juego')),
                ('n_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.usuario')),
            ],
        ),
    ]
