# Generated by Django 3.2.8 on 2021-10-19 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20211012_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='valoracion',
            field=models.IntegerField(null=True, verbose_name='Valoracion'),
        ),
        migrations.AddField(
            model_name='juego',
            name='genero',
            field=models.CharField(max_length=100, null=True, verbose_name='Genero'),
        ),
    ]
