# Generated by Django 3.2.8 on 2021-11-28 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20211019_1727'),
    ]

    operations = [
        migrations.DeleteModel(
            name='comentario',
        ),
        migrations.DeleteModel(
            name='juego',
        ),
    ]
