# Generated by Django 3.2.8 on 2021-11-02 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='imagen',
            field=models.ImageField(upload_to='media/images/'),
        ),
    ]
