# Generated by Django 3.2.8 on 2021-11-02 05:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('perfil', '0004_auto_20211102_0448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='n_usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
    ]
