# Generated by Django 3.2.8 on 2021-11-02 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0005_alter_perfil_n_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='imagen',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
