# Generated by Django 3.2.8 on 2021-11-28 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0009_alter_perfil_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='imagen',
            field=models.ImageField(blank=True, default='foto-generica.jpg', null=True, upload_to='images/'),
        ),
    ]
