# Generated by Django 3.2.8 on 2021-11-28 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('juego', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='juego',
            name='valoracion',
        ),
    ]
